config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :categories
  get 'users/new'
  get 'users/create'
  get 'users/update'
  get 'users/destroy'
  devise_for :users
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'splash#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :expenses
  has_one_attached :icon

  validates :name, :icon, presence: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :category

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :trackable

  attribute :locked_at, :datetime
  has_many :categories
  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionView::Helpers::UrlHelper

  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(_resource)
    categories_path
  end

  protected

  def configure_permitted_parameters
    attributes = [:name]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories.order(created_at: :desc)
    @total_amount = current_user.categories.joins(:expenses).sum('expenses.amount')
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.build(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find_by(id: params[:category_id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon, :image)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[show edit update destroy]

  # GET /expenses or /expenses.json
  def index
    @expenses = Expense.all.order(created_at: :desc)
    @categories = Category.all
  end

  # GET /expenses/1 or /expenses/1.json
  def show
    @expense = Expense.find(params[:id])
    @category = @expense.category
    @expenses = @category.expenses.order(created_at: :desc)
    @total_amount = @category.expenses.sum(:amount)

    return unless @expense.nil?

    flash.now[:notice] = 'No expense for this category.'
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit; end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to expense_url(@expense), notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_expense
    @expense = Expense.find(params[:id])
  end

  def expense_params
    params.require(:expense).permit(:name, :amount, :category_id)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if user_signed_in?
      redirect_to categories_path
    else
      @users = User.all
    end
  end

  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     redirect_to users_path, notice: 'User was successfully created.'
  #   else
  #     render :new
  #   end
  # end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User was successfully destroyed.'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Icon</th>
      <th>Total Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.icon %></td>
        <td><%= category.expenses.sum(:amount) %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/_form.html.erb
<div class="container-fluid">
<div class="col header2">
  <div class="row">
    <div class="col-4 col1">
      <%= link_to categories_path do %>
        <%= image_tag 'back-arrow.png', alt: 'Back', class: 'back-icon' %>
      <% end %>
    </div>
    <div class="col col2">New Category</div>
  </div>
</div>
  <%= form_with(model: category, url: categories_path, local: true, html: { multipart: true }) do |form| %>
    <% if category.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
          <% category.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field form-group">
      <%= form.text_field :name, placeholder: 'Enter name here' %>
    </div>
    <div class="field form-group">
      <%= form.file_field :icon, direct_upload: true %>
    </div>
    <div class="field form-group">
      <%= form.text_field :user_id, placeholder: 'Enter user_id' %>
    </div>
</div>
    <div class="btn-new2">
    <%= form.submit "Create Category", class:"neew" %>
    </div>
  <% end %>
</div>

app/views/categories/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container-fluid">
    <div class="d-flex align-items-center">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <%= link_to 'Category', categories_path, class: "navbar-brand mx-auto text-center" %>
      
      <form class="d-flex">
        <i class="fa-solid fa-magnifying-glass"></i>
      </form>
    </div>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Most ancient', categories_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-primary nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log In', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Register', new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid flld">
  <div class="row gift">
    <div class="col">
      <h4>Gift Credit</h4>
    </div>
    <div class="col sec">
      <h4><%= number_to_currency(@total_amount, unit: '$') %></h4>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="container-fluid catag">
  <div class="row ">
    <% @categories.each do |category| %>
      <div class="row catago" onclick="window.location.href='<%= category.expenses.present? ? expense_path(category.expenses.first) : expenses_path(category_id: category.id) %>';">
        <div class="col">
          <div class="image-container">
          <% if category.icon.attached? %>
          <%= image_tag category.icon, class: "category-icon img-fluid" %>
        <% else %>
          <p>No Image</p>
        <% end %>
          </div>
        </div>

        <div class="col">
          <p><%= category.name %></p>
          <% created_date = category.created_at.strftime('%e%p %B %Y').strip %>
          <% formatted_date = created_date.sub(/\d+(st|nd|rd|th)/, '\1') %>
          <p><%= formatted_date %></p>
        </div>

        <div class="col">
          <% expense = category.expenses.first %>
          <% if expense %>
            <p><%= number_to_currency(expense.amount, unit: '$') %></p>
          <% else %>
            <p>No Expense</p>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="btn-new">
  <%= link_to "New category", new_category_path, class:"neew" %>
  </div> 
</div>
  </div>
  

app/views/categories/new.html.erb
<%= render "form", category: @category %>

<br>

<div>
  
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>">
  <p>
    <strong>Name:</strong>
    <%= expense.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= expense.amount %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= expense.category_id %>
  </p>

</div>

app/views/expenses/_form.html.erb
<div class="card">
  <div class="card-header">
<%= form_with(model: expense) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div class="field form-group">

  <div class="field form-group">
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div class="field form-group">
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>

app/views/expenses/_header.html.erb
<div class="col header2">
  <div class="row">
    <div class="col-4 col1">
      <%= link_to categories_path do %>
        <%= image_tag 'back-arrow.png', alt: 'Back', class: 'back-icon' %>
      <% end %>
    </div>
    <div class="col col2">TRANSACTIONS</div>
  </div>
</div>
<div class="container-fluid flld">
  <div class="row gift">
    <div class="col">
      <h4>Gift Credit</h4>
    </div>
    <div class="col sec">
      <h4><%= number_to_currency(@total_amount, unit: '$') %></h4>
    </div>
  </div>
</div>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">

  <% @categories.each do |category| %>
    
    <div class="row category-total">
   
      <div class="col expense">
      <% category.expenses.each do |expense| %>
        <%= render expense %>
       
        </div>
        <div class="col expense">
          <%= link_to "Show this expense", expense %>
        </div>
      <% end %>
    </div>
  <% end %>
  <%= link_to "New expense", new_expense_path %> </br>
<%= link_to "Back", categories_path %>
</div>

app/views/expenses/new.html.erb
<div class="col header3">
  <div class="row">
    <div class="col-4 col1">
      <%= link_to categories_path do %>
        <%= image_tag 'back-arrow.png', alt: 'Back', class: 'back-icon' %>
      <% end %>
    </div>
    <div class="col col2">New Expense</div>
  </div>
</div>
<%= form_with(model: @expense, url: expenses_path, local: true) do |form| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>
      <ul>
        <% @expense.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field form-group">
    <%= form.text_field :name, placeholder:"Name" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :amount, placeholder:"Amount" %>
  </div>

  <div class="field form-group">
    <%= form.collection_select :category_id, Category.all, :id, :name, prompt: true, placeholder:"category_id" %>
  </div>

  <div class="btn-new2">
    <%= form.submit "Add transaction", class:"neew" %>
    </div>
  <% end %>
</div>
</div>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render "expenses/header" %>

<div class="container-fluid new">
  <div class="row new3">

    <div class="col-12">
      <div class="d-flex ">
        <div class=" col image-container">
          <% if @category.icon.attached? %>
            <%= image_tag @category.icon, class: "category-icon img-fluid" %>
          <% else %>
            <p>No Image</p>
          <% end %>
        </div>

        <div class="col nameex">
          <h3><%= @category.name %></h3>
          <p><%= @category.created_at.strftime('%e%p %B %Y').strip %></p>
        </div>

        <div class="col ml-3 nameex2 ">
        <% if @category.expenses.present? %>
          <% @expenses.each do |expense| %>
              <div class="mt-3">
                <h5><%= number_to_currency(expense.amount, unit: '$') %></h5>
              </div>
              <div class="col">
                <%= link_to expense, method: :delete, class:'btn', data: { confirm: 'Are you sure?' } do %>
                  <%= image_tag 'blue-delete.png', alt: 'Delete', class: 'delete-icon' %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% else %>
          <p>No expenses for this category.</p>
        <% end %>
      </div>

    </div>
  </div>
  </div>

<footer class="container-fluid">
  <div class="justify-content-center new2">
    <%= link_to "Create Expense", new_expense_path(category_id: @category.id), class: "btn cl" %>
  </div>
</footer>

app/views/expenses/show_no_expense.html.erb
<p>No expense for this category.</p>
<%= link_to "Create Expense", new_expense_path(category_id: @category.id) %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Budget</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <% if current_page?(categories_path) %>
  <%= render partial: 'categories/header', locals: { category: @category } %>
  <% elsif current_page?(expenses_path) %>
  <%= render partial: 'expenses/header', locals: { expense: @expense } %>
  <% end %>

  <%= yield %>
  

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
   
  </body>
</html>

app/views/splash/index.html.erb
<div class="container-fluid truck">
  <div class="row heading">
    <h1>TransactionCost</h1>
  </div>
  <div class="row actions in">
  <div class="col text-center">
  <%= link_to "LOG IN", user_session_path, class: "white-link" %>
  </div>
</div>
  <div class="row actions up">
  <div class="col text-center">
    <%= link_to "SIGN UP", new_user_registration_path, class: "white" %>
    </div>
  </div>
 
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>